import { DEFAULT_AUDIO_SETTINGS } from "@/lib/audio/types";
import type { MarketplaceListing } from "@/lib/domain";

export const MARKETPLACE_SEED: MarketplaceListing[] = [
  {
    id: "mkp-sleep-ramp",
    title: "Velvet Descent",
    creator: "stillpoint",
    creatorBadge: "Founding Member",
    type: "program",
    tags: ["sleep", "calm"],
    trendScore: 98,
    createdAt: "2026-02-28T10:12:00.000Z",
    preview: {
      ...DEFAULT_AUDIO_SETTINGS,
      mode: "binaural",
      carrierHz: 180,
      entrainmentHz: 2.5,
    },
  },
  {
    id: "mkp-focus-lock",
    title: "Gamma Vigil 40",
    creator: "Mara Volkov",
    creatorBadge: "Verified",
    type: "preset",
    tags: ["focus", "custom"],
    trendScore: 93,
    createdAt: "2026-03-01T21:20:00.000Z",
    preview: {
      ...DEFAULT_AUDIO_SETTINGS,
      mode: "isochronic",
      carrierHz: 430,
      entrainmentHz: 18,
      waveform: "square",
    },
  },
  {
    id: "mkp-calm-reset",
    title: "Twelve Quiet Minutes",
    creator: "TheQuietRoom",
    type: "program",
    tags: ["calm", "meditation"],
    trendScore: 90,
    createdAt: "2026-03-02T06:08:00.000Z",
    preview: {
      ...DEFAULT_AUDIO_SETTINGS,
      mode: "binaural",
      carrierHz: 240,
      entrainmentHz: 7.5,
      waveform: "triangle",
    },
  },
  {
    id: "mkp-earth-hum",
    title: "Earth Hum 7.83",
    creator: "stillpoint",
    creatorBadge: "Founding Member",
    type: "preset",
    tags: ["meditation", "calm"],
    trendScore: 88,
    createdAt: "2026-04-14T19:42:00.000Z",
    preview: {
      ...DEFAULT_AUDIO_SETTINGS,
      mode: "binaural",
      carrierHz: 432,
      entrainmentHz: 7.83,
    },
  },
  {
    id: "mkp-miracle-morning",
    title: "528 Morning Ritual",
    creator: "Aurelia Finch",
    creatorBadge: "Verified",
    type: "program",
    tags: ["meditation", "custom"],
    trendScore: 86,
    createdAt: "2026-05-02T07:30:00.000Z",
    preview: {
      ...DEFAULT_AUDIO_SETTINGS,
      mode: "binaural",
      carrierHz: 528,
      entrainmentHz: 10,
    },
  },
  {
    id: "mkp-theta-gate",
    title: "Theta Gate",
    creator: "JJDeepCurrent",
    type: "preset",
    tags: ["sleep", "meditation"],
    trendScore: 82,
    createdAt: "2026-05-21T23:05:00.000Z",
    preview: {
      ...DEFAULT_AUDIO_SETTINGS,
      mode: "binaural",
      carrierHz: 211,
      entrainmentHz: 4.5,
    },
  },
];
